name: ci-golang-workflow
on:
    push:
jobs:
    check-application:
        runs-on: ubuntu-latests
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setuo-go@v2
              with:
                  go-version: 1.15
            - run: go test
            - run: go run math.go
